// Mocks generated by Mockito 5.4.6 from annotations
// in termux_flutter_ide/test/terminal/terminal_session_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i12;

import 'package:dartssh2/src/http/http_client.dart' as _i7;
import 'package:dartssh2/src/sftp/sftp_client.dart' as _i6;
import 'package:dartssh2/src/socket/ssh_socket.dart' as _i2;
import 'package:dartssh2/src/ssh_algorithm.dart' as _i3;
import 'package:dartssh2/src/ssh_client.dart' as _i10;
import 'package:dartssh2/src/ssh_forward.dart' as _i4;
import 'package:dartssh2/src/ssh_session.dart' as _i5;
import 'package:dartssh2/src/ssh_signal.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:termux_flutter_ide/termux/termux_bridge.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSSHSocket_0 extends _i1.SmartFake implements _i2.SSHSocket {
  _FakeSSHSocket_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSSHAlgorithms_1 extends _i1.SmartFake implements _i3.SSHAlgorithms {
  _FakeSSHAlgorithms_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSSHForwardChannel_2 extends _i1.SmartFake
    implements _i4.SSHForwardChannel {
  _FakeSSHForwardChannel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSSHSession_3 extends _i1.SmartFake implements _i5.SSHSession {
  _FakeSSHSession_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSftpClient_4 extends _i1.SmartFake implements _i6.SftpClient {
  _FakeSftpClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSSHHttpClient_5 extends _i1.SmartFake implements _i7.SSHHttpClient {
  _FakeSSHHttpClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamSink_6<S> extends _i1.SmartFake implements _i8.StreamSink<S> {
  _FakeStreamSink_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTermuxResult_7 extends _i1.SmartFake implements _i9.TermuxResult {
  _FakeTermuxResult_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SSHClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSSHClient extends _i1.Mock implements _i10.SSHClient {
  MockSSHClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SSHSocket get socket => (super.noSuchMethod(
        Invocation.getter(#socket),
        returnValue: _FakeSSHSocket_0(
          this,
          Invocation.getter(#socket),
        ),
      ) as _i2.SSHSocket);

  @override
  String get username => (super.noSuchMethod(
        Invocation.getter(#username),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#username),
        ),
      ) as String);

  @override
  _i3.SSHAlgorithms get algorithms => (super.noSuchMethod(
        Invocation.getter(#algorithms),
        returnValue: _FakeSSHAlgorithms_1(
          this,
          Invocation.getter(#algorithms),
        ),
      ) as _i3.SSHAlgorithms);

  @override
  bool get disableHostkeyVerification => (super.noSuchMethod(
        Invocation.getter(#disableHostkeyVerification),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> get done => (super.noSuchMethod(
        Invocation.getter(#done),
        returnValue: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> get authenticated => (super.noSuchMethod(
        Invocation.getter(#authenticated),
        returnValue: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i10.SSHRemoteForward?> forwardRemote({
    String? host,
    int? port,
    _i10.SSHRemoteConnectionFilter? filter,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #forwardRemote,
          [],
          {
            #host: host,
            #port: port,
            #filter: filter,
          },
        ),
        returnValue: _i8.Future<_i10.SSHRemoteForward?>.value(),
      ) as _i8.Future<_i10.SSHRemoteForward?>);

  @override
  _i8.Future<bool> cancelForwardRemote(_i10.SSHRemoteForward? forward) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelForwardRemote,
          [forward],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i4.SSHForwardChannel> forwardLocal(
    String? remoteHost,
    int? remotePort, {
    String? localHost = 'localhost',
    int? localPort = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #forwardLocal,
          [
            remoteHost,
            remotePort,
          ],
          {
            #localHost: localHost,
            #localPort: localPort,
          },
        ),
        returnValue:
            _i8.Future<_i4.SSHForwardChannel>.value(_FakeSSHForwardChannel_2(
          this,
          Invocation.method(
            #forwardLocal,
            [
              remoteHost,
              remotePort,
            ],
            {
              #localHost: localHost,
              #localPort: localPort,
            },
          ),
        )),
      ) as _i8.Future<_i4.SSHForwardChannel>);

  @override
  _i8.Future<_i5.SSHSession> execute(
    String? command, {
    _i10.SSHPtyConfig? pty,
    Map<String, String>? environment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [command],
          {
            #pty: pty,
            #environment: environment,
          },
        ),
        returnValue: _i8.Future<_i5.SSHSession>.value(_FakeSSHSession_3(
          this,
          Invocation.method(
            #execute,
            [command],
            {
              #pty: pty,
              #environment: environment,
            },
          ),
        )),
      ) as _i8.Future<_i5.SSHSession>);

  @override
  _i8.Future<_i5.SSHSession> shell({
    _i10.SSHPtyConfig? pty = const _i10.SSHPtyConfig(),
    Map<String, String>? environment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #shell,
          [],
          {
            #pty: pty,
            #environment: environment,
          },
        ),
        returnValue: _i8.Future<_i5.SSHSession>.value(_FakeSSHSession_3(
          this,
          Invocation.method(
            #shell,
            [],
            {
              #pty: pty,
              #environment: environment,
            },
          ),
        )),
      ) as _i8.Future<_i5.SSHSession>);

  @override
  _i8.Future<void> subsystem(String? subsystem) => (super.noSuchMethod(
        Invocation.method(
          #subsystem,
          [subsystem],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i6.SftpClient> sftp() => (super.noSuchMethod(
        Invocation.method(
          #sftp,
          [],
        ),
        returnValue: _i8.Future<_i6.SftpClient>.value(_FakeSftpClient_4(
          this,
          Invocation.method(
            #sftp,
            [],
          ),
        )),
      ) as _i8.Future<_i6.SftpClient>);

  @override
  _i7.SSHHttpClient httpClient() => (super.noSuchMethod(
        Invocation.method(
          #httpClient,
          [],
        ),
        returnValue: _FakeSSHHttpClient_5(
          this,
          Invocation.method(
            #httpClient,
            [],
          ),
        ),
      ) as _i7.SSHHttpClient);

  @override
  _i8.Future<_i12.Uint8List> run(
    String? command, {
    bool? runInPty = false,
    bool? stdout = true,
    bool? stderr = true,
    Map<String, String>? environment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #run,
          [command],
          {
            #runInPty: runInPty,
            #stdout: stdout,
            #stderr: stderr,
            #environment: environment,
          },
        ),
        returnValue: _i8.Future<_i12.Uint8List>.value(_i12.Uint8List(0)),
      ) as _i8.Future<_i12.Uint8List>);

  @override
  _i8.Future<void> ping() => (super.noSuchMethod(
        Invocation.method(
          #ping,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handlePacket(_i12.Uint8List? packet) => super.noSuchMethod(
        Invocation.method(
          #handlePacket,
          [packet],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SSHSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockSSHSession extends _i1.Mock implements _i5.SSHSession {
  MockSSHSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.StreamSink<_i12.Uint8List> get stdin => (super.noSuchMethod(
        Invocation.getter(#stdin),
        returnValue: _FakeStreamSink_6<_i12.Uint8List>(
          this,
          Invocation.getter(#stdin),
        ),
      ) as _i8.StreamSink<_i12.Uint8List>);

  @override
  _i8.Stream<_i12.Uint8List> get stdout => (super.noSuchMethod(
        Invocation.getter(#stdout),
        returnValue: _i8.Stream<_i12.Uint8List>.empty(),
      ) as _i8.Stream<_i12.Uint8List>);

  @override
  _i8.Stream<_i12.Uint8List> get stderr => (super.noSuchMethod(
        Invocation.getter(#stderr),
        returnValue: _i8.Stream<_i12.Uint8List>.empty(),
      ) as _i8.Stream<_i12.Uint8List>);

  @override
  _i8.Future<void> get done => (super.noSuchMethod(
        Invocation.getter(#done),
        returnValue: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void write(_i12.Uint8List? data) => super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resizeTerminal(
    int? width,
    int? height, [
    int? pixelWidth = 0,
    int? pixelHeight = 0,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #resizeTerminal,
          [
            width,
            height,
            pixelWidth,
            pixelHeight,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void kill(_i13.SSHSignal? signal) => super.noSuchMethod(
        Invocation.method(
          #kill,
          [signal],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [TermuxBridge].
///
/// See the documentation for Mockito's code generation for more information.
class MockTermuxBridge extends _i1.Mock implements _i9.TermuxBridge {
  MockTermuxBridge() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> isTermuxInstalled() => (super.noSuchMethod(
        Invocation.method(
          #isTermuxInstalled,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i9.TermuxResult> executeCommand(
    String? command, {
    String? workingDirectory,
    bool? background = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeCommand,
          [command],
          {
            #workingDirectory: workingDirectory,
            #background: background,
          },
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #executeCommand,
            [command],
            {
              #workingDirectory: workingDirectory,
              #background: background,
            },
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<_i9.TermuxResult> runFlutterCommand(String? subCommand) =>
      (super.noSuchMethod(
        Invocation.method(
          #runFlutterCommand,
          [subCommand],
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #runFlutterCommand,
            [subCommand],
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<_i9.TermuxResult> flutterRun({String? target}) =>
      (super.noSuchMethod(
        Invocation.method(
          #flutterRun,
          [],
          {#target: target},
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #flutterRun,
            [],
            {#target: target},
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<_i9.TermuxResult> flutterBuildApk({bool? release = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #flutterBuildApk,
          [],
          {#release: release},
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #flutterBuildApk,
            [],
            {#release: release},
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<_i9.TermuxResult> flutterDoctor() => (super.noSuchMethod(
        Invocation.method(
          #flutterDoctor,
          [],
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #flutterDoctor,
            [],
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<String?> getTermuxPrefix() => (super.noSuchMethod(
        Invocation.method(
          #getTermuxPrefix,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<int?> getTermuxUid() => (super.noSuchMethod(
        Invocation.method(
          #getTermuxUid,
          [],
        ),
        returnValue: _i8.Future<int?>.value(),
      ) as _i8.Future<int?>);

  @override
  _i8.Future<_i9.ExternalAppsStatus> checkExternalAppsAllowed() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkExternalAppsAllowed,
          [],
        ),
        returnValue: _i8.Future<_i9.ExternalAppsStatus>.value(
            _i9.ExternalAppsStatus.allowed),
      ) as _i8.Future<_i9.ExternalAppsStatus>);

  @override
  _i8.Future<_i9.TermuxResult> enableExternalApps() => (super.noSuchMethod(
        Invocation.method(
          #enableExternalApps,
          [],
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #enableExternalApps,
            [],
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<bool> checkTermuxPrefix() => (super.noSuchMethod(
        Invocation.method(
          #checkTermuxPrefix,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> checkSSHServiceStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkSSHServiceStatus,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> openTermux() => (super.noSuchMethod(
        Invocation.method(
          #openTermux,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> openTermuxSettings() => (super.noSuchMethod(
        Invocation.method(
          #openTermuxSettings,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<String?> getTermuxPackageInstaller() => (super.noSuchMethod(
        Invocation.method(
          #getTermuxPackageInstaller,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> checkPermission(String? permission) => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [permission],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> launchTermux() => (super.noSuchMethod(
        Invocation.method(
          #launchTermux,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> openBatteryOptimizationSettings() => (super.noSuchMethod(
        Invocation.method(
          #openBatteryOptimizationSettings,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> canDrawOverlays() => (super.noSuchMethod(
        Invocation.method(
          #canDrawOverlays,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i9.TermuxResult> setupTermuxSSH() => (super.noSuchMethod(
        Invocation.method(
          #setupTermuxSSH,
          [],
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #setupTermuxSSH,
            [],
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<_i9.TermuxResult> setupStorage() => (super.noSuchMethod(
        Invocation.method(
          #setupStorage,
          [],
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #setupStorage,
            [],
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<_i9.TermuxResult> installFlutter() => (super.noSuchMethod(
        Invocation.method(
          #installFlutter,
          [],
        ),
        returnValue: _i8.Future<_i9.TermuxResult>.value(_FakeTermuxResult_7(
          this,
          Invocation.method(
            #installFlutter,
            [],
          ),
        )),
      ) as _i8.Future<_i9.TermuxResult>);

  @override
  _i8.Future<bool> isFlutterInstalled() => (super.noSuchMethod(
        Invocation.method(
          #isFlutterInstalled,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Stream<String> executeCommandStream(
    String? command, {
    String? workingDirectory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeCommandStream,
          [command],
          {#workingDirectory: workingDirectory},
        ),
        returnValue: _i8.Stream<String>.empty(),
      ) as _i8.Stream<String>);

  @override
  _i8.Future<void> fixTermuxEnvironment() => (super.noSuchMethod(
        Invocation.method(
          #fixTermuxEnvironment,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
