include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "test/**"
    - "integration_test/**"
  errors:
    avoid_print: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    unnecessary_to_list_in_spreads: ignore
    invalid_use_of_visible_for_testing_member: ignore
    unused_import: ignore
    unused_local_variable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    prefer_final_fields: ignore
    unrelated_type_equality_checks: ignore
    unnecessary_import: ignore
    curly_braces_in_flow_control_structures: ignore
    use_build_context_synchronously: ignore
    unnecessary_brace_in_string_interps: ignore
    library_private_types_in_public_api: ignore
    sort_child_properties_last: ignore
