// Mocks generated by Mockito 5.4.6 from annotations
// in termux_flutter_ide/test/setup/environment_check_interaction_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:termux_flutter_ide/termux/termux_bridge.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTermuxResult_0 extends _i1.SmartFake implements _i2.TermuxResult {
  _FakeTermuxResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TermuxBridge].
///
/// See the documentation for Mockito's code generation for more information.
class MockTermuxBridge extends _i1.Mock implements _i2.TermuxBridge {
  MockTermuxBridge() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isTermuxInstalled() => (super.noSuchMethod(
        Invocation.method(
          #isTermuxInstalled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i2.TermuxResult> executeCommand(
    String? command, {
    String? workingDirectory,
    bool? background = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeCommand,
          [command],
          {
            #workingDirectory: workingDirectory,
            #background: background,
          },
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #executeCommand,
            [command],
            {
              #workingDirectory: workingDirectory,
              #background: background,
            },
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<_i2.TermuxResult> runFlutterCommand(String? subCommand) =>
      (super.noSuchMethod(
        Invocation.method(
          #runFlutterCommand,
          [subCommand],
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #runFlutterCommand,
            [subCommand],
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<_i2.TermuxResult> flutterRun({String? target}) =>
      (super.noSuchMethod(
        Invocation.method(
          #flutterRun,
          [],
          {#target: target},
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #flutterRun,
            [],
            {#target: target},
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<_i2.TermuxResult> flutterBuildApk({bool? release = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #flutterBuildApk,
          [],
          {#release: release},
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #flutterBuildApk,
            [],
            {#release: release},
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<_i2.TermuxResult> flutterDoctor() => (super.noSuchMethod(
        Invocation.method(
          #flutterDoctor,
          [],
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #flutterDoctor,
            [],
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<String?> getTermuxPrefix() => (super.noSuchMethod(
        Invocation.method(
          #getTermuxPrefix,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<int?> getTermuxUid() => (super.noSuchMethod(
        Invocation.method(
          #getTermuxUid,
          [],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  _i3.Future<_i2.ExternalAppsStatus> checkExternalAppsAllowed() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkExternalAppsAllowed,
          [],
        ),
        returnValue: _i3.Future<_i2.ExternalAppsStatus>.value(
            _i2.ExternalAppsStatus.allowed),
      ) as _i3.Future<_i2.ExternalAppsStatus>);

  @override
  _i3.Future<_i2.TermuxResult> enableExternalApps() => (super.noSuchMethod(
        Invocation.method(
          #enableExternalApps,
          [],
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #enableExternalApps,
            [],
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<bool> checkTermuxPrefix() => (super.noSuchMethod(
        Invocation.method(
          #checkTermuxPrefix,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> checkSSHServiceStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkSSHServiceStatus,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> openTermux() => (super.noSuchMethod(
        Invocation.method(
          #openTermux,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> openTermuxSettings() => (super.noSuchMethod(
        Invocation.method(
          #openTermuxSettings,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> getTermuxPackageInstaller() => (super.noSuchMethod(
        Invocation.method(
          #getTermuxPackageInstaller,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<bool> checkPermission(String? permission) => (super.noSuchMethod(
        Invocation.method(
          #checkPermission,
          [permission],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> launchTermux() => (super.noSuchMethod(
        Invocation.method(
          #launchTermux,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> openBatteryOptimizationSettings() => (super.noSuchMethod(
        Invocation.method(
          #openBatteryOptimizationSettings,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> canDrawOverlays() => (super.noSuchMethod(
        Invocation.method(
          #canDrawOverlays,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<_i2.TermuxResult> setupTermuxSSH() => (super.noSuchMethod(
        Invocation.method(
          #setupTermuxSSH,
          [],
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #setupTermuxSSH,
            [],
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<_i2.TermuxResult> setupStorage() => (super.noSuchMethod(
        Invocation.method(
          #setupStorage,
          [],
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #setupStorage,
            [],
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<_i2.TermuxResult> installFlutter() => (super.noSuchMethod(
        Invocation.method(
          #installFlutter,
          [],
        ),
        returnValue: _i3.Future<_i2.TermuxResult>.value(_FakeTermuxResult_0(
          this,
          Invocation.method(
            #installFlutter,
            [],
          ),
        )),
      ) as _i3.Future<_i2.TermuxResult>);

  @override
  _i3.Future<bool> isFlutterInstalled() => (super.noSuchMethod(
        Invocation.method(
          #isFlutterInstalled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Stream<String> executeCommandStream(
    String? command, {
    String? workingDirectory,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeCommandStream,
          [command],
          {#workingDirectory: workingDirectory},
        ),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Future<void> fixTermuxEnvironment() => (super.noSuchMethod(
        Invocation.method(
          #fixTermuxEnvironment,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
